' Module   : CONFIG.BAS
' Project  : Example module-based program using Future Library.
' Purpose  : Configuration functions and sub-routines.
' Modified : 2025-07-10 -- Aligned the colons in the header.

' $INCLUDE: 'C:\QBX\DECLARE.BI'
' $INCLUDE: 'C:\BC7\FL35\FUTURE.BI'

SUB ConfigManager (Mode$, Setting$)

' NOTE: The ConfigManager is called to open or save settings
' ----- via a CONFIG.INI file. Also checks to see if it exists.

' TODO: Open and save Setting$ depending on Mode$...

END SUB

SUB ConfigOpen (Setting$)

' TODO: Open settings from a CONFIG.INI file...

END SUB

SUB ConfigSave (Setting$)

' TODO: Save settings to a CONFIG.INI file...

END SUB

